name: Run tests

on:
  push: 
    branches: [main]
    
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: instalar deps do server
        uses: bahmutov/npm-install@v1
        with:
          working-directory: server
      - name: instalar deps do server
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web
      - name: Component & API & UI Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          installs: false
          start: npm run start:ci
          wait-on: 'http://localhost:3000'
